# Generated by Django 4.1 on 2022-10-29 17:25

from django.db import migrations, models
import speakers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('affiliation', models.CharField(max_length=75)),
                ('country', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('profile', models.TextField()),
                ('photo_file', models.ImageField(upload_to=speakers.models.user_directory_path)),
                ('storage_path', models.CharField(max_length=100)),
                ('speech_title', models.CharField(max_length=100)),
                ('speach_abstract', models.TextField()),
                ('time', models.TimeField()),
                ('room', models.CharField(max_length=20)),
                ('symposium', models.CharField(max_length=100)),
            ],
        ),
    ]
