# Generated by Django 4.1 on 2022-11-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('affiliation', models.CharField(max_length=75)),
                ('country', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('profile', models.TextField()),
                ('storagePath', models.CharField(max_length=100)),
                ('speechTitle', models.CharField(max_length=100, null=True)),
                ('speechAbstract', models.TextField()),
                ('time', models.DateTimeField()),
                ('room', models.CharField(max_length=20)),
                ('symposium', models.CharField(max_length=100)),
            ],
        ),
    ]
