# Generated by Django 4.1 on 2022-10-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakers',
            old_name='photo_file',
            new_name='photoFilename',
        ),
        migrations.RenameField(
            model_name='speakers',
            old_name='speach_abstract',
            new_name='speechAbstract',
        ),
        migrations.RenameField(
            model_name='speakers',
            old_name='speech_title',
            new_name='storagePath',
        ),
        migrations.RemoveField(
            model_name='speakers',
            name='storage_path',
        ),
        migrations.AddField(
            model_name='speakers',
            name='speechTitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
