# Generated by Django 4.1 on 2022-11-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_rename_photo_file_speakers_photofilename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
