# Generated by Django 4.1 on 2022-11-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0005_alter_speakers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
