# Generated by Django 4.1 on 2022-11-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0006_alter_speakers_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakers',
            old_name='id',
            new_name='s_id',
        ),
    ]
