# Generated by Django 4.1 on 2022-10-29 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('affiliation', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=30)),
                ('speakerType', models.CharField(max_length=20)),
                ('profile', models.TextField()),
                ('photoFilename', models.TextField()),
                ('storagePath', models.TextField()),
                ('speechTitle', models.TextField()),
                ('speechAbstract', models.TextField()),
                ('time', models.CharField(max_length=15)),
                ('room', models.CharField(max_length=50)),
                ('symposium', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symposium', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventsParallel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.tracks')),
            ],
        ),
        migrations.CreateModel(
            name='EventsGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=15)),
                ('program', models.TextField()),
                ('place', models.CharField(max_length=50)),
                ('isParallel', models.BooleanField()),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.speakers')),
            ],
        ),
    ]
