# Generated by Django 4.1 on 2022-10-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventsgeneral_time_eventsgeneral_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
