# Generated by Django 4.1 on 2022-10-30 03:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_speakers_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track2',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('symposium', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventsparallel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='eventsparallel',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='eventsparallel',
            name='time',
        ),
        migrations.AddField(
            model_name='eventsparallel',
            name='endTime',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsparallel',
            name='event_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='events.eventsgeneral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsparallel',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='events.speakers'),
        ),
        migrations.AddField(
            model_name='eventsparallel',
            name='startTime',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventsparallel',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.track2'),
        ),
        migrations.DeleteModel(
            name='Tracks',
        ),
    ]
