# Generated by Django 4.1 on 2022-10-30 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_track2_remove_eventsparallel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsparallel',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='events.eventsgeneral'),
        ),
    ]
