# Generated by Django 4.1 on 2022-10-30 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventsparallel_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsparallel',
            name='event_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.RESTRICT, to='events.eventsgeneral'),
        ),
    ]
