# Generated by Django 4.1 on 2022-10-30 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_track2_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsparallel',
            name='eventId',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.RESTRICT, to='events.eventsgeneral'),
        ),
        migrations.AlterField(
            model_name='track2',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
