# Generated by Django 4.1 on 2022-10-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventsparallel_eventid_alter_track2_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsgeneral',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
