# Generated by Django 4.1 on 2022-10-30 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_eventsgeneral_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsparallel',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 30)),
            preserve_default=False,
        ),
    ]
