# Generated by Django 4.1 on 2022-10-30 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_alter_submission_notified_and_more'),
        ('events', '0011_eventsparallel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsparallel',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='submission.track'),
        ),
    ]
