# Generated by Django 4.1 on 2022-10-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_rename_photo_file_speakers_photofilename_and_more'),
        ('events', '0012_alter_eventsparallel_program'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track2',
        ),
        migrations.AlterField(
            model_name='eventsgeneral',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='speakers.speakers'),
        ),
        migrations.AlterField(
            model_name='eventsparallel',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='speakers.speakers'),
        ),
        migrations.DeleteModel(
            name='Speakers',
        ),
    ]
