# Generated by Django 4.1 on 2022-10-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='username',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
