# Generated by Django 4.1 on 2022-10-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_testimonial_user_testimonial_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='username',
            field=models.CharField(default='Guest', max_length=255),
        ),
    ]
